# Generated by Django 3.2.5 on 2021-07-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='follow_product',
        ),
        migrations.AddField(
            model_name='product',
            name='follow_product',
            field=models.ManyToManyField(to='products.FollowUpProduct'),
        ),
    ]
