# Generated by Django 3.2.5 on 2021-07-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organs', '0006_auto_20210731_1849'),
        ('products', '0002_auto_20210731_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationProduct',
        ),
        migrations.AlterField(
            model_name='product',
            name='follow_product',
            field=models.ManyToManyField(to='organs.OrganizationProduct'),
        ),
    ]
