version: '3'
#volumes:
#  CrmDbData:
services:
  database:
    image: "postgres:10-alpine"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: usr_crm
      POSTGRES_PASSWORD: 123456
      PGPASSWORD: 123456
      POSTGRES_DB: maktab_crm
      PGDATA: /db_data
#    volumes:
#      - CrmDbData:/db_data
#  cache:
#    image: "memcached:alpine"
#    ports:
#      - 11211:11211
#  broker:
#    image: "rabbitmq:alpine"
#    ports:
#      - 5672:5672
