# Generated by Django 3.2.5 on 2021-07-31 18:45

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210731_1845'),
        ('organs', '0004_alter_organization_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationProduct',
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='employees_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_product',
            field=models.ManyToManyField(to='products.OrganizationProduct'),
        ),
    ]
